// The little stories people tell when you stop by with nothing in particular to talk about: each kind of person their own pool,
// drawn without repeats till a pool is used up (bag()). Kept apart from quests.js so they are easy to add to.
// (All made up: no real people, places or brands.)
export const ANECDOTES = {
  police: [
    'WCZORAJ GONILIŚMY KURĘ PRZEZ TRZY OSIEDLA. KURA WYGRAŁA. KOMENDANT KAZAŁ NIE WPISYWAĆ DO RAPORTU.',
    'MÓJ KOLEGA WYPISAŁ MANDAT SAM SOBIE. ZAPARKOWAŁ NA KOPERCIE I SIĘ NIE ZAUWAŻYŁ. ZAPŁACIŁ. RATALNIE.',
    'TEN RADIOWÓZ PALI TYLE CO CZOŁG, A JEŹDZI WOLNIEJ NIŻ TWÓJ ROWER. JAK GONIMY, TO DZWONIMY, ŻEBY ZACZEKALI.',
    'RAZ ZATRZYMAŁEM BABCIĘ ZA PRĘDKOŚĆ. NA CHODZIKU. Z GÓRKI. SZEŚĆDZIESIĄT NA GODZINĘ. POUCZENIE DOSTAŁEM JA.',
    'KOMENDANT KAZAŁ NAM BIEGAĆ DLA KONDYCJI. TO TERAZ BIEGAMY. DO SKLEPU. CZĘŚCIEJ.',
    'PODOBNO W BARAKACH MAJĄ WIĘCEJ ROWERÓW, NIŻ MY MAMY SPRAWNYCH RADIOWOZÓW. JA TAM NIE SPRAWDZAŁEM. BOJĘ SIĘ PSA.',
    'NA POSTERUNKU MIESZKA KOT. NIKT NIE WIE CZYJ. MA WŁASNĄ SZAFKĘ. I LEPSZE KRZESŁO NIŻ JA.',
    'TRZY LATA TEMU KTOŚ UKRADŁ NAM SYRENĘ. Z RADIOWOZU. JAK GO GONILIŚMY, TO ON MIAŁ SYGNAŁ, A MY NIE.',
    'MIELIŚMY ZGŁOSZENIE, ŻE KTOŚ WYJE W NOCY POD BLOKIEM. POJECHALIŚMY. TO BYŁ KOMENDANT. WRACAŁ Z IMIENIN.',
    'NAJTRUDNIEJSZA SPRAWA W MOJEJ KARIERZE? ZAGINIONY PILOT OD TELEWIZORA. ZNALAZŁ SIĘ W LODÓWCE. SPRAWCA NIE ZOSTAŁ USTALONY.',
    'U NAS NA SZKOLENIU STRZELAŁEM TAK ŹLE, ŻE INSTRUKTOR SCHOWAŁ SIĘ ZA TARCZĄ. MÓWIŁ, ŻE TAM NAJBEZPIECZNIEJ.',
    'RAZ ZATRZYMAŁEM PANA, CO WIÓZŁ NA ROWERZE SZAFĘ. PYTAM: A PAN DOKĄD? A ON: DO DOMU, PANIE WŁADZO, PRZECIEŻ NIE DO SZAFY.',
    'MAMY NA POSTERUNKU EKSPRES DO KAWY Z DOWODÓW RZECZOWYCH. NIKT NIE PYTA, SKĄD. KAWA DOBRA.',
    'SĄSIADKA ZGŁASZA CO TYDZIEŃ, ŻE KTOŚ JEJ KRADNIE KWIATKI. CO TYDZIEŃ JEDZIEMY. CO TYDZIEŃ TO JEJ KOZA.',
    'PIES TROPIĄCY NAM ODSZEDŁ NA EMERYTURĘ. ZNACZY ZNALAZŁ KIEŁBASĘ W CZYIMŚ GARAŻU I TAM ZOSTAŁ. DOBRZE MU.',
    'NAJWIĘKSZY POŚCIG W HISTORII KOMISARIATU: TRAKTOR KONTRA RADIOWÓZ. TRZY GODZINY. TRAKTOR STANĄŁ, BO SKOŃCZYŁA MU SIĘ ROPA. NAM TEŻ.',
    'KIEDYŚ ZAMKNĘLIŚMY SIĘ SAMI W CELI. KLUCZ BYŁ U KOTA. DŁUGO NEGOCJOWALIŚMY.',
    'MANDAT ZA ŚPIEWANIE W MIEJSCU PUBLICZNYM? JEST TAKI. WYPISAŁEM GO RAZ. SOBIE. NA WIGILII KOMISARIATU.' ],
  belly: [
    'JA KIEDYŚ BYŁEM SZYBSZY NIŻ TY, MŁODY. W PODSTAWÓWCE. RAZ. GONIŁ MNIE INDYK.',
    'WIESZ, CZEMU MAM TAKI BRZUCH? BO SERCE MAM DUŻE. I TRZEBA BYŁO GDZIEŚ ZROBIĆ MIEJSCE.',
    'ŻONA MÓWI, ŻE LEŻAK TO NIE PRACA. A JA MÓWIĘ: KTOŚ MUSI PILNOWAĆ ULICY. I PILNUJĘ. Z ZAMKNIĘTYMI OCZAMI, ALE PILNUJĘ.',
    'RAZ ZŁOWIŁEM SZCZUPAKA TAKIEGO, ŻE ON MNIE CIĄGNĄŁ PO JEZIORZE. DO DZIŚ NIE WIEM, KTO KOGO ZŁOWIŁ.',
    'NA WESELU SZWAGRA TAŃCZYŁEM TAK, ŻE ORKIESTRA PRZESTAŁA GRAĆ. ZE STRACHU.',
    'KUPIŁEM KIEDYŚ ROWER. JEŹDZIŁEM DWA DNI. TRZECIEGO DNIA ROWER POWIEDZIAŁ: DOŚĆ. ZNACZY PĘKŁA RAMA.',
    'MÓJ DZIADEK MÓWIŁ: SYNKU, NIE BIEGAJ, BO SIĘ SPOCISZ. I TAK ŻYJĘ. SUCHO.',
    'SĄSIAD MA KOSIARKĘ SPALINOWĄ. JA MAM KOZĘ. KOZA TAŃSZA I NIE TRZEBA LAĆ PALIWA. TYLKO ZJADA TEŻ KWIATKI ŻONIE.' ],
  old: [
    'ZA MOICH CZASÓW GAZETY BYŁY GRUBSZE. BO MIAŁY W ŚRODKU PRAWDĘ. I PROGRAM TELEWIZYJNY.',
    'MÓJ ŚWIĘTEJ PAMIĘCI ROZWOZIŁ MLEKO KONIEM. KOŃ ZNAŁ TRASĘ LEPIEJ NIŻ ON. RAZ ZOSTAWIŁ GO W GOSPODZIE I KOŃ ROZWIÓZŁ SAM.',
    'JA W TWOIM WIEKU CHODZIŁAM DO SZKOŁY DZIESIĘĆ KILOMETRÓW. POD GÓRKĘ. W OBIE STRONY. TAKA BYŁA GEOGRAFIA.',
    'WNUCZEK MI ZAŁOŻYŁ TEN, NO, INTERNET. TERAZ WIEM, CO SIĘ DZIEJE NA ŚWIECIE. I NIE MOGĘ SPAĆ.',
    'NASZA ULICA KIEDYŚ BYŁA POLNĄ DROGĄ. JAK PADAŁO, TO AUTOBUS PŁYWAŁ. MÓWILIŚMY NA NIEGO STATEK.',
    'POZNALIŚMY SIĘ NA ZABAWIE W REMIZIE. NADEPNĄŁ MI NA NOGĘ TRZY RAZY. ZA TRZECIM RAZEM POWIEDZIAŁAM: NO TO SIĘ ŻEŃ.',
    'MOJA SĄSIADKA MA SZEŚĆ KOTÓW. MÓWI, ŻE TO ONE MAJĄ JĄ. CHYBA MA RACJĘ.',
    'KIEDYŚ ROZWOZIŁ TU GAZETY TAKI JEDEN, CO RZUCAŁ PROSTO DO KOMINA. ZAWSZE TRAFIAŁ. POTEM POSZEDŁ DO WOJSKA. DO ARTYLERII.',
    'DZIADEK MÓJ MÓWIŁ, ŻE NAJLEPSZE LEKARSTWO TO CEBULA. NA WSZYSTKO. ŻYŁ DZIEWIĘĆDZIESIĄT LAT. SAM. BO NIKT NIE CHCIAŁ PODCHODZIĆ.' ],
  lads: [
    'MÓWIĄ, ŻE TU KIEDYŚ BYŁA FABRYKA. TERAZ JESTEŚMY MY. ZNACZY SIĘ PRODUKCJA RUSZYŁA.',
    'ZIUTEK RAZ ZAŁOŻYŁ SIĘ, ŻE PRZESKOCZY BECZKĘ Z OGNIEM. PRZESKOCZYŁ. TYLKO SPODNIE NIE.',
    'MAMY TU TELEWIZOR NA KORBĘ. KRĘCISZ, TO LECI PROGNOZA POGODY. ZAWSZE TA SAMA. Z OSIEMDZIESIĄTEGO SZÓSTEGO.',
    'KIEDYŚ PRZYJECHAŁ TU PAN Z URZĘDU, ŻE NAS WYSIEDLAJĄ. ZOSTAŁ NA OGNISKU DO RANA. TERAZ PRZYCHODZI W PIĄTKI.',
    'NASZ PIES NAZYWA SIĘ KOMORNIK. JAK GO WOŁAMY, TO PÓŁ OSIEDLA ZAMYKA OKNA.',
    'W ZESZŁYM ROKU UPIEKLIŚMY W BECZCE KURCZAKA. TEN KURCZAK DO DZIŚ JEST LEGENDĄ. I DO DZIŚ GO JEMY.',
    'MAREK MÓWI, ŻE BYŁ KIEDYŚ MARYNARZEM. NA JEZIORZE. NA ROWERKU WODNYM. TRZY SEZONY.',
    'NIE MAMY TU ADRESU, ALE LISTONOSZ I TAK DO NAS TRAFIA. BO GO KARMIMY.' ],
  stop: [
    'TEN AUTOBUS JEŹDZI TAK RZADKO, ŻE RAZ CZEKAŁAM NA NIEGO TAK DŁUGO, AŻ SKOŃCZYŁAM SWETER. NA DRUTACH. DLA WNUKA. A WNUK URÓSŁ.',
    'KIEROWCA SIÓDEMKI TO MÓJ SZWAGIER. JAK MNIE WIDZI, TO NIE STAJE. MÓWI, ŻE WIE, CO MU POWIEM.',
    'NA TYM PRZYSTANKU POZNAŁAM MĘŻA. CZEKALIŚMY NA TEN SAM AUTOBUS. NIE PRZYJECHAŁ. TO SIĘ POBRALIŚMY.',
    'ROZKŁAD JAZDY TO TAKA LITERATURA FANTASTYCZNA. CZYTAM DLA PRZYJEMNOŚCI.',
    'RAZ AUTOBUS PRZYJECHAŁ PUNKTUALNIE. WSZYSCY STALIŚMY ZE ZDZIWIENIA I NIKT NIE WSIADŁ. ODJECHAŁ PUSTY.',
    'TEN PAN NA ŁAWCE ŚPI TU OD WIOSNY. MÓWI, ŻE CZEKA NA OSTATNI KURS. NIKT MU NIE MÓWI, ŻE GO ZLIKWIDOWALI.' ],
  lump: [
    'JA TU NIE ŚPIĘ, MŁODY. JA OBSERWUJĘ RUCH. Z ZAMKNIĘTYMI OCZAMI LEPIEJ SŁYCHAĆ AUTOBUSY.',
    'KIEDYŚ BYŁEM DYREKTOREM. CZEGO? TEGO PRZYSTANKU. SAM SIĘ MIANOWAŁEM. NIKT NIE PROTESTOWAŁ.',
    'RAZ ZNALAZŁEM STÓWĘ. KUPIŁEM ZA NIĄ LOS NA LOTERII. WYGRAŁEM PIĘĆDZIESIĄT. TO JESTEM DO PRZODU? NIE WIEM, NIE LICZĘ.',
    'MÓJ BRAT JEST W POLICJI. ZNACZY... ON TAK MÓWI. SIEDZI NA POSTERUNKU CODZIENNIE. W CELI.',
    'WIESZ, CO JEST NAJLEPSZE NA PRZYSTANKU? DACH. I ŁAWKA. I ŻE NIKT NIE KAŻE CI NIGDZIE JECHAĆ.',
    'KIEDYŚ JA TEŻ ROZWOZIŁEM GAZETY. ALE CZYTAŁEM JE PO DRODZE. KLIENCI DOSTAWALI JUŻ PRZECZYTANE. NIKT NIE NARZEKAŁ.' ],
};
// Pan Janusz from the bike shop: an old-school cyclist (shorts, flip-flops, a tank top too small, a cap, a belly): his trips with Mietek
ANECDOTES.janusz = [
  'Z MIETKIEM JECHALIŚMY KIEDYŚ NAD MORZE. TRZYSTA KILOMETRÓW. NA JEDNYM BIEGU. W KLAPKACH. MORZA NIE ZOBACZYLIŚMY, BO MIETEK ZOSTAŁ NA FESTYNIE W POŁOWIE DROGI.',
  'RAZ ZŁAPAŁEM GUMĘ W LESIE. ŁATKI NIE MIAŁEM. ZAŁATAŁEM KANAPKĄ Z SEREM. DOJECHAŁEM. SER NIE.',
  'W OSIEMDZIESIĄTYM ÓSMYM WYGRAŁEM WYŚCIG GMINNY. BYŁEM JEDYNY, KTÓRY NIE ZABŁĄDZIŁ. RESZTA POJECHAŁA ZA KROWAMI.',
  'Z MIETKIEM JECHALIŚMY W GÓRY. ON MÓWI: POD GÓRKĘ PROWADZIMY. JA MÓWIĘ: KTO PROWADZI, TEN NIE JEDZIE. PROWADZILIŚMY TRZY DNI.',
  'LYCRA? SYNKU, JA JEŻDŻĘ W KRÓTKICH GACIACH I KLAPKACH. AERODYNAMIKA JEST W GŁOWIE. A BRZUCH DAJE STABILNOŚĆ.',
  'KIEDYŚ GONIŁ MNIE PIES PRZEZ TRZY WSIE. W KAŻDEJ WSI BYŁ INNY PIES. TEN TRZECI BYŁ NAJSZYBSZY, ALE MIAŁ KRÓTKIE ŁAPY. JAK TEN MÓJ KOLEGA Z WOJSKA.',
  'ROWER, NA KTÓRYM JEŹDZIŁEM DO SZKOŁY, JEŹDZI DO DZIŚ. JEŹDZI NA NIM SĄSIAD. UKRADŁ MI GO W DZIEWIĘĆDZIESIĄTYM PIERWSZYM. NIE GNIEWAM SIĘ, DBA O NIEGO.',
  'MIETEK KUPIŁ KIEDYŚ ROWER Z DWUDZIESTOMA BIEGAMI. UŻYWAŁ DWÓCH. RESZTA, MÓWIŁ, JEST NA CZARNĄ GODZINĘ.',
  'NAJDŁUŻSZA TRASA W MOIM ŻYCIU? DO TEŚCIOWEJ. CZTERDZIEŚCI KILOMETRÓW. A WYDAWAŁO SIĘ, ŻE CZTERYSTA.',
  'RAZ ZAMONTOWAŁEM KLIENTOWI KIEROWNICĘ ODWROTNIE. JEŹDZI TAK DO DZIŚ. MÓWI, ŻE MA LEPSZY WIDOK NA BUTY.',
  'Z MIETKIEM POJECHALIŚMY NA ZLOT ROWEROWY. ZLOT BYŁ TYDZIEŃ WCZEŚNIEJ. ALE PIWO BYŁO, WIĘC ZLOT SIĘ ODBYŁ. W DWÓCH OSOBACH.',
  'NA TANDEMIE JECHAŁEM RAZ Z ŻONĄ. ONA Z TYŁU. PO DZIESIĘCIU KILOMETRACH SIĘ ODWRACAM, A JEJ NIE MA. ZOSTAŁA W CUKIERNI. JA PEDAŁOWAŁEM ZA DWOJE.' ];
export const JANUSZ = {
  hello: ['SIEMA, MŁODY. WITAJ W NAJLEPSZYM WARSZTACIE NA TRASIE. INNYCH NIE MA, ALE TO NIE ZMIENIA FAKTU.', 'O, KLIENT! SIADAJ. ZNACZY NIE SIADAJ, BO TO MÓJ TABORET.',
    'NO CO TAM SKRZYPI? BO COŚ SKRZYPI. U MNIE ZAWSZE COŚ SKRZYPI. NAJCZĘŚCIEJ KOLANO.', 'MŁODY, ZA MOICH CZASÓW JEŹDZIŁO SIĘ NA DAMCE Z KOSZYKIEM I NIKT NIE PŁAKAŁ. A TY CO DZIŚ?',
    'WCHODŹ, WCHODŹ. TYLKO NIE DOTYKAJ TEGO W KĄCIE. TO NIE ZŁOM, TO KOLEKCJA.'],
  cats: { kola: ['KOŁO TO PODSTAWA. JAK MÓWIŁ MÓJ OJCIEC: KOŁO SIĘ KRĘCI, INTERES SIĘ KRĘCI.', 'SZOSÓWKI? DLA TYCH W OBCISŁYCH GACIACH. ALE JEŻDŻĄ, NIE POWIEM.'],
    siodelko: ['SIODEŁKO, MŁODY, TO NIE JEST MIEJSCE NA OSZCZĘDNOŚCI. TYŁEK MASZ JEDEN.', 'ŻELOWE TO JAK FOTEL. JA MAM ŻELOWE. I BRZUCH. PODWÓJNA AMORTYZACJA.'],
    kierownica: ['KIEROWNICA BMX? TO JUŻ NIE ROWER, TO STYL ŻYCIA.', 'CHWYTY SPORTOWE. ŻEBY RĘCE SIĘ NIE POCIŁY. MI SIĘ POCĄ I TAK, ALE JA JESTEM WYJĄTKIEM.'],
    biegi: ['PRZERZUTKI TYLKO JAPOŃSKIE, MŁODY. NIE JAKIEŚ BADZIEWIE Z BAZARU, CO PO TYGODNIU SKACZE JAK KOZA.', 'SIEDEM BIEGÓW. MIETEK MIAŁ DWADZIEŚCIA I UŻYWAŁ DWÓCH. TY UŻYJESZ TRZECH, ZNAM CIĘ.'],
    lakier: ['LAKIER TO DUSZA ROWERU. CZARNY MAT? CHCESZ BYĆ NINJA OD GAZET?', 'MIĘTOWY... ŻONA BY WZIĘŁA MIĘTOWY. TO JUŻ COŚ MÓWI.'],
    dzwonek: ['DZWONEK TO NIE OZDOBA. TO ARGUMENT.', 'DRYŃ! I BABCIA SCHODZI Z DROGI. ALBO CIĘ ZBIJE LASKĄ. RÓŻNIE.'],
    lampka: ['LAMPKA? PRZEPISOWO. JA JEŹDZIŁEM BEZ, ALE JA ZNAM KAŻDĄ DZIURĘ NA PAMIĘĆ. PO IMIENIU.', 'Z LAMPKĄ POLICJA PATRZY ŁASKAWIEJ. SPRAWDZONE NA MIETKU.'],
    torba: ['WIĘKSZA TORBA, WIĘCEJ GAZET, WIĘCEJ KASY. MATEMATYKA, MŁODY.', 'LISTONOSZOWA. PO LISTONOSZU. ON TERAZ JEŹDZI SKUTEREM I UDAJE, ŻE MNIE NIE ZNA.'] },
  buy: ['DOBRY WYBÓR. JA BYM WZIĄŁ TO SAMO. ZNACZY WZIĄŁBYM DROŻSZE, ALE TO TEŻ DOBRE.', 'ZAMONTOWANE. NIE PYTAJ, CZEMU ZOSTAŁA MI JEDNA ŚRUBKA.', 'NO! TERAZ TO JEST MASZYNA! LUDZIE BĘDĄ SIĘ OGLĄDAĆ. ZA ROWEREM, NIE ZA TOBĄ.', 'GOTOWE. GWARANCJA DO ROGU ULICY.', 'PRZYKRĘCONE NA SZTYWNO. JAK MÓJ KRĘGOSŁUP.'],
  broke: ['MŁODY, ZA DARMO TO JA MOGĘ CI OPOWIEDZIEĆ, JAK BYŁO NAD MORZEM.', 'KASY BRAK? TO ROZWOŹ GAZETY, A NIE OGLĄDAJ WYSTAWY.', 'NA KRECHĘ NIE DAJĘ. MIETEK MI WISI OD DZIEWIĘĆDZIESIĄTEGO SZÓSTEGO.'],
  sell: ['TO? NO DOBRA, WEZMĘ. WSZYSTKO KIEDYŚ SIĘ PRZYDA, MAM GARAŻ JAKO DOWÓD.', 'HO, HO. TO SIĘ NADA. NA CO, NIE WIEM. ALE SIĘ NADA.'],
  fill: ['GAZETY? DOBRZE, ŻE NIE KIEŁBASA. KIEŁBASY BYM NIE ODDAŁ.'],
  bye: ['JEDŹ Z BOGIEM, MŁODY. I SMARUJ ŁAŃCUCH!', 'TYLKO NIE WRACAJ Z ÓSEMKĄ W KOLE!', 'POZDRÓW ZIUTKA, JAK GO SPOTKASZ. I NIE POŻYCZAJ MU POMPKI.'],
  bark: ['MŁODY! ŁAŃCUCH CI SKRZYPI, SŁYSZĘ STĄD!', 'ZAJEDŹ, ZROBIMY Z TEGO ROWER!', 'JAPOŃSKI OSPRZĘT, MŁODY! JAPOŃSKI!', 'KASK? JA MAM CZAPKĘ! OD TRZYDZIESTU LAT TĘ SAMĄ!', 'ZA MOICH CZASÓW TO SIĘ JEŹDZIŁO!', 'HAMULCE MASZ JAK TEŚCIOWA: NIBY SĄ, A NIE DZIAŁAJĄ!'] };
// a pool drawn without repeats: once used up, shuffled again
export function bag() {
  const left = {};
  const draw = key => { const all = ANECDOTES[key] || []; if (!left[key] || !left[key].length) { left[key] = all.slice(); for (let i = left[key].length - 1; i > 0; i--) { const j = Math.random() * (i + 1) | 0; [left[key][i], left[key][j]] = [left[key][j], left[key][i]]; } } return left[key].pop() || ''; };
  return { draw, reset: () => { for (const k in left) delete left[k]; } };
}
