// What is said at a fight's end (docs/fabula.md: each one his own voice; black humour, never the same line twice in a row of fights):
// by the region it is fought in, and by who he is. win: he (the player) won, the one lying there says it; lose: he lost, the winner says it.
// endLine(region, kind, outcome) → a line: the region's and the man's lines in one deck, shuffled, none again till all have come.
const REGION = {
  peryferia: { win: ['DOBRA, DOBRA. TYLKO NIE MÓW MOJEJ ŻONIE. ONA MYŚLI, ŻE JESTEM GROŹNY.', 'LEŻĘ, BO CHCĘ. TRAWA TU JEST ŚWIEŻO SKOSZONA.', 'JUTRO SPOTKAMY SIĘ NA ZEBRANIU WSPÓLNOTY. I WTEDY ZOBACZYSZ.', 'PANI Z NAPRZECIWKA WSZYSTKO WIDZIAŁA. JUŻ DZWONI DO MOJEJ MATKI.'],
    lose: ['I TAK SIĘ KOŃCZY ROZNOSZENIE GAZET NA NASZEJ ULICY. ZAPAMIĘTAJ.', 'POZDRÓW JANUSZA. POWIEDZ, ŻE ROWER MA DO ROBOTY. TY TEŻ.', 'NO I CO? MAMA CI PLASTER PRZYKLEI.', 'TU SIĘ JEŹDZI WOLNO. TERAZ JUŻ WIESZ DLACZEGO.'] },
  wies: { win: ['NIECH TO GĘSI ROZDZIOBIĄ... ZNACZY: GRATULUJĘ.', 'NA WSI MÓWIĄ, ŻE KTO LEŻY, TEN ODPOCZYWA. ODPOCZYWAM.', 'SOŁTYS SIĘ DOWIE. SOŁTYS ZAWSZE SIĘ DOWIADUJE.', 'BIŁEM SIĘ Z BYKIEM I WYGRAŁEM. Z TOBĄ NIE. COŚ MI NIE PASUJE.'],
    lose: ['MIASTOWY. WIDAĆ PO PIĘŚCIACH.', 'U NAS TAK SIĘ WITA GOŚCI. POTEM JEST BIGOS.', 'IDŹ, ZANIM KRÓWKI ZOBACZĄ, JAK LEŻYSZ.', 'PRZEKAŻ W MIEŚCIE, ŻE WIEŚ SIĘ NIE PODDAJE.'] },
  peryferia2: { win: ['ZAPISZ W RAPORCIE: WYPADEK PRZY PRACY.', 'MAGAZYNIER Z DWUDZIESTOLETNIM STAŻEM. LEŻY. HISTORIA.', 'BHP MÓWIŁO, ŻEBY NIE CHODZIĆ BEZ KASKU. TERAZ ROZUMIEM.', 'NA ZMIANIE NOCNEJ BYŁEM BY LEPSZY. TERAZ JEST RANEK.'],
    lose: ['NASTĘPNYM RAZEM PRZYJDŹ W KAMIZELCE ODBLASKOWEJ. ŻEBY CIĘ ZNALEŹLI.', 'TU SIĘ PRACUJE RĘKAMI, MŁODY. WIDZIAŁEŚ?', 'ROZŁADUNEK SKOŃCZONY. TY TEŻ.', 'DŹWIG WIDZIAŁ. DŹWIG NIC NIE POWIE.'] },
  miasto: { win: ['PROSZĘ BEZ ZDJĘĆ. TURYŚCI JUŻ PATRZĄ.', 'KAMIENICA PAMIĘTA WIĘKSZE BÓJKI. ALE NIE Z MOIM UDZIAŁEM.', 'TRAMWAJ JEDZIE. NIE MAM SIŁY WSIĄŚĆ.', 'W MIEŚCIE TO SIĘ NAZYWA „KONFLIKT INTERESÓW”. JA PRZEGRAŁEM INTERES.'],
    lose: ['WITAMY W CENTRUM. PARKING PŁATNY, LEŻENIE GRATIS.', 'MIASTO NIE LUBI POŚPIECHU. TERAZ MASZ CZAS.', 'ODDAJ SIĘ W RĘCE STRAŻY MIEJSKIEJ. JAK PRZYJADĄ. CZYLI NIGDY.', 'TU NIKT NIC NIE WIDZIAŁ. TO JEST MIASTO.'] },
  bronx: { win: ['DOBRA, KOLARZ. RESPEKT. ALE TYLKO DZISIAJ.', 'NA OSIEDLU SIĘ TEGO NIE ZAPOMINA. ANI TOBIE, ANI MNIE.', 'PRZEKAŻ NA KLATCE, ŻE SIĘ POŚLIZGNĄŁEM.', 'LATARNIA ZGASŁA W ZŁYM MOMENCIE. LATARNIA JEST WINNA.'],
    lose: ['TU SIĘ NIE PRZYJEŻDŻA PO CIEMKU, MŁODY.', 'OSIEDLE CIĘ ZAPAMIĘTA. NIE NA DOBRE.', 'GAZETY ZOSTAWIASZ, SIEBIE ZABIERASZ. TAKA UMOWA.', 'NASTĘPNYM RAZEM DZWOŃ DOMOFONEM. MOŻE KTOŚ OTWORZY.'] } };
const KIND = {
  cherlak: { win: ['TO SIĘ NIE LICZY, MIAŁEM ROZWIĄZANE SZNURÓWKI!', 'DOBRA, NIECH BĘDZIE. MAMA I TAK MÓWIŁA, ŻEBYM SIĘ NIE BIŁ.', 'JA TYLKO SPRAWDZAŁEM, JAK TWARDY JEST CHODNIK. BARDZO.'],
    lose: ['HAHA! WYGRAŁEM! ...CZEKAJ, NA SERIO WYGRAŁEM?', 'POWIEM WSZYSTKIM. NIKT MI NIE UWIERZY, ALE POWIEM.', 'KOPNIAK W KOSTKĘ, TAJNA TECHNIKA DZIADKA.'] },
  kozak: { win: ['TO BYŁA ROZGRZEWKA. PRAWDZIWA WALKA JEST JUTRO. MOŻE.', 'DAŁEM CI WYGRAĆ. ŻEBYŚ MIAŁ MOTYWACJĘ.', 'NIKT NIE WIDZIAŁ? NIKT NIE WIDZIAŁ. SUPER.'],
    lose: ['MÓWIŁEM, ŻE JESTEM KOZAK? TO TERAZ WIESZ.', 'PRZEKAŻ DALEJ: KOZAK Z OSIEDLA NIE PRZEGRYWA. PRAWIE NIGDY.', 'POZUJ DO ZDJĘCIA. DO MOJEGO ZDJĘCIA.'] },
  szwagier: { win: ['DOBRA... JUŻ DOBRA. NA WESELU I TAK BĘDZIEMY SIEDZIEĆ PRZY JEDNYM STOLE.', 'TEŚCIOWA MNIE NIE BIJE TAK SKUTECZNIE. A PRÓBUJE.', 'IDŹ JUŻ. TYLKO NIE MÓW SZWAGROWI. ZNACZY, TO JA JESTEM SZWAGIER.'],
    lose: ['TAK SIĘ ROZMAWIA PO RODZINNEMU.', 'NA IMIENINACH OPOWIEM. TY TEŻ OPOWIESZ, TYLKO INACZEJ.', 'NIC OSOBISTEGO. ZNACZY TROCHĘ OSOBISTEGO.'] },
  kurier: { win: ['KURIER OSIEDLOWY WRÓCI. MAMY WIĘCEJ ROWERÓW NIŻ WY GAZET.', 'TO NIC. MEGAFON MA UBEZPIECZENIE OD TAKICH JAK TY.', 'ZGŁOSZĘ TO DO CENTRALI. CENTRALA LUBI ZGŁOSZENIA.'],
    lose: ['TWOJE GAZETY SĄ TERAZ NASZE. FAKTURĘ PRZEŚLEMY.', 'MEGAFON POZDRAWIA TRĄBKĘ. GŁOŚNO.', 'NAJSZYBSZY GAZECIARZ W DZIELNICY? NO TO DRUGI NAJSZYBSZY.'] } };
const decks = {};
let s = 7; const rnd = () => { s = (s * 16807) % 2147483647; return s / 2147483647; };
export function endLine(region, kind, outcome) {
  const key = region + '|' + kind + '|' + outcome; let d = decks[key];
  if (!d || !d.length) { const pool = [...(REGION[region] || REGION.peryferia)[outcome], ...((KIND[kind] || KIND.kozak)[outcome])]; d = decks[key] = pool.sort(() => rnd() - .5); }
  return d.pop();
}
